import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY;

// Initialize the client once.
// Note: In a production app, handle the case where API_KEY is missing gracefully.
const ai = new GoogleGenAI({ apiKey: apiKey || '' });

/**
 * Edits an image based on a text prompt using Gemini.
 * @param base64Image The image data in base64 format (without the data:image/png;base64, prefix).
 * @param mimeType The mime type of the image (e.g., 'image/png').
 * @param prompt The user instruction for editing.
 * @returns The edited image as a base64 data URL.
 */
export const editImageWithGemini = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing. Please set the API_KEY environment variable.");
  }

  try {
    const model = 'gemini-2.5-flash-image';
    
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      // Config for image editing/generation usually requires specific strict handling
      // but defaults often work well for 2.5 flash image.
    });

    // Parse response for image data
    const parts = response.candidates?.[0]?.content?.parts;
    
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          const newMime = part.inlineData.mimeType || 'image/png';
          return `data:${newMime};base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
